name: release

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14.15'
          registry-url: 'https://registry.npmjs.org'

      - name: Install
        run: npm i

      - name: Build
        run: npm run build:prod

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
